### ISSUE TITLE
Chardet: Expected object of type bytes or bytearray, got: <class 'int'>

### ISSUE THREAD

**Issue by lmolent** [keitaoouchi/easyimap#43]
>>> import easyimap
>>> imapper = easyimap.connect(....)
>>> m = imapper.unseen()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/stackstorm/virtualenvs/email/lib/python3.6/site-packages/easyimap/easyimap.py", line 174, in unseen
    return self.listup(limit, 'UNSEEN')
  File "/opt/stackstorm/virtualenvs/email/lib/python3.6/site-packages/easyimap/easyimap.py", line 192, in listup
    mail = _parse_email(content, include_raw=include_raw)
  File "/opt/stackstorm/virtualenvs/email/lib/python3.6/site-packages/easyimap/easyimap.py", line 247, in _parse_email
    encoding = chardet.detect(string_or_bytes_message)
  File "/opt/stackstorm/virtualenvs/email/lib/python3.6/site-packages/chardet/__init__.py", line 34, in detect
    '{0}'.format(type(byte_str)))
TypeError: Expected object of type bytes or bytearray, got: <class 'int'>

**Comment by gassajor000** [comment]
Also seeing this error (oddly not consistently, even with the same message). It seems sometimes the mailer.uid() method returns an extra FLAGS entry in the content variable.

**Comment by gassajor000** [comment]
> Also seeing this error (oddly not consistently, even with the same message). 

Update: After doing some digging I'm pretty sure that the extra entry in the content variable was a flags update. It would only appear when I changed the UNSEEN flag via the outlook web app. Neither imaplib nor easyimap seem to be setup to handle these flag updates.

**Comment by anirudhbagri** [comment]
any luck how we can get this to work?
I am also facing the same issue.

The issue is with the mail whose UNSEEN flag has been changed using outlook client.
